name: ElevenWorkflow
on:
  push
run-name: "Testing vars"
env:
  WF_CUSTOM_VAR: WF 1    

jobs:
  
  testing-vars1:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: JOB 1 
    steps:
      - name: Vars
        env:
          STEP_CUSTOM_VAR: STEP 1
        run: | 
          echo $GITHUB_REF
          echo "${{ github.ref }}"
          echo $WF_CUSTOM_VAR
          echo "${{ env.WF_CUSTOM_VAR }}"
          echo $JOB_CUSTOM_VAR
          echo $STEP_CUSTOM_VAR
  