name: TwelveWorkflow
on:
  push
run-name: "Testing secrets"

jobs:
  
  run-first-command:
    runs-on: ubuntu-latest

    steps:

      - name: Vars and Secrets
        run: | 
          echo "${{ secrets.PASSWORD }}"
          echo "${{ vars.STATUS }}"


  