name: 17thWorkflow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom title"
        type: string
        default: "Testing text title"
        required: false
jobs:
    call-workflow:
      uses: ./.github/workflows/workflow.yml
      with:
        title: ${{ inputs.title }}
    call-external-workflow:
        uses: ug4nd/workflows/.github/workflows/workflow.yml@main
        secrets:
            PASSWORD: ${{ secrets.PASSWORD }}