name: FifthWorkflow
on: [push, issues]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Event arguments Github
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REF