name: FourthWorkflow
on:
  workflow_run:
    workflows: [ThirdWorkflow]
    types:
      - completed    

jobs:
  success_command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: For success
        run: echo "Success! Its good"
  failure_command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: For error
        run: echo "Error! Change something"
