name: NinehWorkflow
on:
  repository_dispatch:
    types: [test]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs
        run: |
          echo "Var: ${{ github.event.client_payload.titleTest }}"

