name: ThirdWorkflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files and copy repo
        run: |
          ls -la
      - uses: actions/checkout@v4
      - name: List files
        run: |
          ls -la      